# Generated by Django 2.1 on 2020-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('信息科学学院', '信息科学学院'), ('经贸院', '经贸院'), ('外国语学院', '外国语学院'), ('中国语言文学系', '中国语言文学系')], default=None, max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.CharField(choices=[('信息科学学院', '信息科学学院'), ('经贸院', '经贸院'), ('外国语学院', '外国语学院'), ('中国语言文学系', '中国语言文学系')], default=None, max_length=20, verbose_name='学院'),
        ),
    ]
